name: publish container
on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/burnskp/containers
      DOCKERFILE: ${{ inputs.dockerfile }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Get container info
      id: container
      env:
        dockerfile: ${{ env.DOCKERFILE }}
      run: |
        echo "name=${dockerfile%%/*}" >> "$GITHUB_OUTPUT"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.token }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
      with:
        images: ${{ env.REGISTRY }}/${{ steps.container.outputs.name }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value={{date 'YYYYMMDD-HHmmss'}}-{{sha}}
    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
      with:
        context: ${{ steps.container.outputs.name }}
        provenance: mode=max
        sbom: true
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
